### ISSUE TITLE
Request for mobx-starter

### ISSUE THREAD

**Issue by worifon** [nightwolfz/ryan#2]
I apologize for this entry, but I have strong request for you.
Please give me a chance to get mobx-starter, I will use it for learning purpose only.
My e-mail address: worifon@gmail.com
Thank you and best regards,

**Comment by nightwolfz** [comment]
I'm sorry, my employer is keeping a close eye on this for some reason.

If I find a completely different way of handling state and actions. I will share it.

Regards,
Ryan

**Comment by mweststrate** [comment]
Really too bad! I loved the setup :) I know the feeling. We have an awesome powered highly interactive app that renders thousands items with drag and drop and such, but not shareable :'( (yet)
